from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(478, 351)
        self.pb = QtWidgets.QPushButton(Form)
        self.pb.setGeometry(QtCore.QRect(360, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb.setFont(font)
        self.pb.setObjectName("pb")
        self.ted1 = QtWidgets.QTextEdit(Form)
        self.ted1.setGeometry(QtCore.QRect(100, 30, 231, 31))
        self.ted1.setObjectName("ted1")
        self.lb1 = QtWidgets.QLabel(Form)
        self.lb1.setGeometry(QtCore.QRect(30, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Headline R")
        font.setPointSize(15)
        self.lb1.setFont(font)
        self.lb1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lb1.setObjectName("lb1")
        self.lb2 = QtWidgets.QLabel(Form)
        self.lb2.setGeometry(QtCore.QRect(30, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Headline R")
        font.setPointSize(15)
        self.lb2.setFont(font)
        self.lb2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lb2.setObjectName("lb2")
        self.pb1 = QtWidgets.QPushButton(Form)
        self.pb1.setGeometry(QtCore.QRect(120, 100, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb1.setFont(font)
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(Form)
        self.pb2.setGeometry(QtCore.QRect(220, 100, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb2.setFont(font)
        self.pb2.setObjectName("pb2")
        self.lbd = QtWidgets.QLabel(Form)
        self.lbd.setGeometry(QtCore.QRect(30, 210, 291, 111))
        self.lbd.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbd.setText("")
        self.lbd.setObjectName("lbd")
        self.lbt = QtWidgets.QLabel(Form)
        self.lbt.setGeometry(QtCore.QRect(30, 170, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbt.setFont(font)
        self.lbt.setObjectName("lbt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb.setText(_translate("Form", "Download"))
        self.lb1.setText(_translate("Form", "Url:"))
        self.lb2.setText(_translate("Form", "Ext."))
        self.pb1.setText(_translate("Form", "mp3"))
        self.pb2.setText(_translate("Form", "mp4"))
        self.lbt.setText(_translate("Form", "Console"))
